version: 1.0.{build}-{branch}
branches:
  only:
  - master
skip_non_tags: true

image: Visual Studio 2019 Preview
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }
build_script:
- cmd: >-
    mkdir build-win-x64
    cd build-win-x64
    cmake -DCMAKE_GENERATOR_PLATFORM=x64 ..
    cd ..
    cmake --build build-win-x64 --config Release
    dir build-win-x64

artifacts:
- path: build-win-x64
